Repository emulsify-ds/gatsby-theme-emulsify-workspace, pull requests merged in 2020-03, with the labels that each got.

#6 File download capability & Example Pages now instructive content
  example/README.md
  example/components/Button/Code.mdx
  example/components/Cta/Code.mdx
  example/styleguide/0__Getting started/0__Welcome.mdx
  example/styleguide/0__Getting started/1__Installation & Usage.md
  example/styleguide/0__Getting started/2__Whatever.md
  example/styleguide/0__Getting started/blank.pdf
  example/styleguide/0__Getting started/logo.svg
  example/styleguide/1__Documentation/0__Colors.md
  example/styleguide/1__Documentation/0__Gatsby.md
  example/styleguide/1__Documentation/1__Storybook.md
  example/styleguide/1__Documentation/1__Typography.md
  example/styleguide/1__Documentation/colors-gray-light.png
  example/styleguide/1__Documentation/colors-gray.png
  example/styleguide/3__Resources/Documentation.md
  example/styleguide/3__Resources/Help.md
  example/styleguide/index.mdx
  gatsby-theme-emulsify/README.md
  gatsby-theme-emulsify/gatsby-config.js
  gatsby-theme-emulsify/package.json
Labels: Status: Review Needed

#5 GS-32: Add Tablinks component for external code navigation
  example/components/00-Button/Code.mdx
  example/components/01-Cta/Code.mdx
  gatsby-theme-emulsify/src/components/Atoms/TabLinks/ExternalIcon.js
  gatsby-theme-emulsify/src/components/Atoms/TabLinks/TabLinks.component.js
  gatsby-theme-emulsify/src/components/Templates/layout.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#8 Gatsby Node Cleanup, Cleaner urls, Page Sorting
  example/components/0__Button/Button.component.js
  example/components/0__Button/Button.css
  example/components/0__Button/Button.stories.js
  example/components/0__Button/Code.mdx
  example/components/0__Button/Style.md
  example/components/0__Button/Usage.md
  example/components/1__Cta/Code.mdx
  example/components/1__Cta/Cta.component.js
  example/components/1__Cta/Cta.css
  example/components/1__Cta/Cta.stories.js
  example/components/1__Cta/Style.md
  example/components/1__Cta/Usage.md
  example/styleguide/1__Documentation/1__Typography.md
  gatsby-theme-emulsify/gatsby-node.js
  gatsby-theme-emulsify/src/components/Molecules/Menus/MainMenu.component.js
  gatsby-theme-emulsify/src/components/Templates/layout.js
Labels: Priority: Medium, Status: Review Needed
